### ISSUE TITLE
Qestion on image paire pattern in "Gaussian Repair Model"

### ISSUE THREAD

**Issue by Beastmaster** [hanyangyu1021/LMGaussian#1]
Thanks for your brillant work!

I have a small question on your paper:  how do you prepare training image pairs when traning the "Gaussian Repair Model". Should the image pairs be paired on the same viewpoints?
I'm also curious about if the sparse view images enough for training.

Thank you,

**Comment by hanyangyu1021** [comment]
Hi, thank you for your interest in our work! Regarding the training image pairs, we utilize pairs that share the same viewpoints to fine-tune a control network. While sparse views alone may not suffice for effective fine-tuning, we implement LoRA to address this limitation. About the image encoder, we use clip feature and sd1.5 vae's encoder. You can view our code for more details. Thanks!
