### ISSUE TITLE
How about the inference speed？

### ISSUE THREAD

**Issue by GuoPingPan** [hanyangyu1021/LMGaussian#4]
Great job! Have you tested the inference speed? What’s the estimated throughput in Hz?

**Comment by hanyangyu1021** [comment]
Thank you for your attention! Our code is based on an optimized framework, and we have incorporated iterative diffusion refinement. Consequently, the training time will be longer than that of the vanilla 3DGS. However, if you are referring to the time required to rasterize a test view after training, it is comparable to the original 3DGS.

**Comment by GuoPingPan** [comment]
Thank you for your thoughtful reply.
