### ISSUE TITLE
ckpt is inexistent

### ISSUE THREAD

**Issue by LiHaodong0217** [hanyangyu1021/LMGaussian#6]
hello @hanyangyu1021 
i want to ask that:[v1-5-pruned.ckpt](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main) is inexistent
so can i use https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5?

**Comment by hanyangyu1021** [comment]
Hi, I have uploaded it to the Google Drive. Feel free to reach out~ 
https://drive.google.com/file/d/1nTv449A9ZzHnhaFXjCchbZYnRVXwdS3k/view?usp=sharing

**Comment by yutian10** [comment]
hello @hanyangyu1021 
I found the model in google drive cannot be loaded by PyTorch.

Here is the error:
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by liu123456-shi** [comment]
I have also encountered this issue. It should be that the weight model is incomplete.
